version: "3"
services:
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/usr/src/app
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    working_dir: /usr/src/app
    command: /bin/sh -c "./entrypoint.sh"

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"