version: "3"
services:
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/usr/src/app
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    working_dir: /usr/src/app
    command: /bin/sh -c "./entrypoint.sh"

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379