name: Automated release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release a new version 🚀
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install modules
      run: npm ci
    - name: Release 🚀
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: true